Squashed commit of branch swing-rewrite:
commit e7d170f6babd798eb690c2571a024b89eeb84b85
Author: Christian Schrötter <cs@fnx.li>
Date:   Sun Mar 22 19:08:59 2020 +0100

    ...

commit 5d63aa641599e157b85bbea219123709b876600b
Author: Christian Schrötter <cs@fnx.li>
Date:   Sun Mar 22 17:41:47 2020 +0100

    ...

commit 9cde42bc404466bc327d6e0cda30e2741eef84ea
Author: Christian Schrötter <cs@fnx.li>
Date:   Sun Mar 22 17:36:51 2020 +0100

    ...

commit ff1941e0802ee4427d0e379607c4d2e9c5c03e11
Author: Christian Schrötter <cs@fnx.li>
Date:   Sun Mar 22 17:26:53 2020 +0100

    ...

commit 4c35a3edf13e9f225316712ac0fe95ac998d17de
Author: Christian Schrötter <cs@fnx.li>
Date:   Sun Mar 8 19:46:50 2020 +0100

    Use type inference wherever possible

commit e3ba6eef3f90a77e8c8619d2cdb70275721c9e7d
Author: Christian Schrötter <cs@fnx.li>
Date:   Sun Mar 8 19:31:33 2020 +0100

    ...

commit c633a2c934d2b7d1dbbeb7cf46fd42c94752893d
Author: Christian Schrötter <cs@fnx.li>
Date:   Tue Mar 3 18:46:47 2020 +0100

    Update Makefile

commit d3e15532c7f3f38571cc1d662dd1f05f17f197fa
Author: Christian Schrötter <cs@fnx.li>
Date:   Tue Mar 3 18:41:56 2020 +0100

    ...

commit 2e063cbdbd68b9ecd2b9dff860dd3d5dbb2bf91d
Author: Christian Schrötter <cs@fnx.li>
Date:   Tue Mar 3 18:29:47 2020 +0100

    sed required

commit 177b9bc37e93be475871e08ca4bcdc0f38fbca12
Author: Christian Schrötter <cs@fnx.li>
Date:   Tue Mar 3 18:27:40 2020 +0100

    native2ascii required

commit f559b9b314d56d4b77ed3a333ef25b83dcef5c2a
Author: Christian Schrötter <cs@fnx.li>
Date:   Tue Mar 3 18:26:29 2020 +0100

    Update SK locales (thanks starec!) and change i18n handling

commit c26c6452be9f26a100abf96d2062de90b2bcaf77
Author: Christian Schrötter <cs@fnx.li>
Date:   Mon Mar 2 18:48:07 2020 +0100

    ...

commit 151d99d15cdb73fd8de4af9ec0bc41fd2214893e
Author: Christian Schrötter <cs@fnx.li>
Date:   Mon Mar 2 18:32:35 2020 +0100

    ...

commit 13b6dedb6b922bd9c98b6e440219ddf737e0aac4
Author: Christian Schrötter <cs@fnx.li>
Date:   Sun Mar 1 02:27:20 2020 +0100

    ...

commit 7de257fa2527839de0d96cfaf6b0966e634e02a2
Author: Christian Schrötter <cs@fnx.li>
Date:   Sun Mar 1 02:23:38 2020 +0100

    Fix #25

commit 7b3c134b7326771732a71fac5f8f29c9e5dfd4fa
Author: Christian Schrötter <cs@fnx.li>
Date:   Sun Mar 1 02:01:06 2020 +0100

    Fix #87

commit f3bf8f7144383c295fd0ab0ceac34c7e2c586be1
Author: Christian Schrötter <cs@fnx.li>
Date:   Sun Mar 1 01:53:11 2020 +0100

    Remove unused compatibility method

commit 74e8d106837864958e454ac46eec6c0e7da781ce
Author: Christian Schrötter <cs@fnx.li>
Date:   Sun Mar 1 01:52:11 2020 +0100

    Fix #70

commit 6b28665bd271f51c844ad9689d31fae20aac5563
Author: Christian Schrötter <cs@fnx.li>
Date:   Sun Mar 1 01:46:56 2020 +0100

    Fix more compiler warnings

commit 8455b08fa9bc6dd08dc4f0be36890e08d40cdc67
Author: Christian Schrötter <cs@fnx.li>
Date:   Sat Feb 29 22:31:55 2020 +0100

    ...

commit ee9de05f40eb2c2394c39cc30601bbaaab21589d
Author: Christian Schrötter <cs@fnx.li>
Date:   Sat Feb 29 22:20:56 2020 +0100

    Fix more compiler warnings

commit a5baf5121ad1237901cb5c56db443fd5e70f6699
Author: Christian Schrötter <cs@fnx.li>
Date:   Sat Feb 29 21:02:36 2020 +0100

    Fix more compiler warnings

commit ceac282c3135c94dbd38646d28d2e71e7946250d
Author: Christian Schrötter <cs@fnx.li>
Date:   Sat Feb 29 19:23:06 2020 +0100

    Fix various compiler warnings

commit 5434205a97bbb54e2f7b52c576b21b4d5ed5b49a
Author: Christian Schrötter <cs@fnx.li>
Date:   Sat Feb 29 18:09:02 2020 +0100

    Move i18n.md logic to Makefile target

commit e9d3b5c43a1eeffd7eeae25831d600807e1de7ac
Author: Christian Schrötter <cs@fnx.li>
Date:   Sat Feb 29 18:07:59 2020 +0100

    Update IT locales (thx RivaStyle!)

commit 86e3889aef8f328ae1bf052c232520fae6f5dac4
Author: Christian Schrötter <cs@fnx.li>
Date:   Thu Feb 20 17:45:50 2020 +0100

    ...

commit 7dd70bd67269e3b8479ef162371f483dcc9f726c
Author: Christian Schrötter <cs@fnx.li>
Date:   Thu Feb 20 16:44:35 2020 +0100

    ...

commit c4f61a05bb83dfb60c093700671b90fb5bcf033e
Author: Christian Schrötter <cs@fnx.li>
Date:   Thu Feb 20 07:29:06 2020 +0100

    ...

commit d0bb811318ed25913080bca155b68bb7958300fc
Author: Christian Schrötter <cs@fnx.li>
Date:   Thu Feb 20 07:28:50 2020 +0100

    ...

commit abb092964b6ac0731620d95d33d6c8f96b7da53e
Author: Christian Schrötter <cs@fnx.li>
Date:   Thu Feb 20 07:09:53 2020 +0100

    ...

commit 0f778304c3b3b28f20a98af1ede6a4ddb5eb21bd
Author: Christian Schrötter <cs@fnx.li>
Date:   Thu Feb 20 03:41:55 2020 +0100

    ENABLE_BLURRY

commit e4a0f259dece1a6c1d591df52414f37fead10e94
Author: Christian Schrötter <cs@fnx.li>
Date:   Thu Feb 20 01:14:27 2020 +0100

    ...

commit 48a36b94535d2737bf07846c34c82e69de6bd8d1
Author: Christian Schrötter <cs@fnx.li>
Date:   Thu Feb 20 00:35:01 2020 +0100

    ...

commit e1707a910293865700c5168623e59da88c21610a
Author: Christian Schrötter <cs@fnx.li>
Date:   Wed Feb 19 23:12:19 2020 +0100

    ...

commit 33ff45b5f7f63a6d4c5f573bc83000f7b3be1d82
Author: Christian Schrötter <cs@fnx.li>
Date:   Wed Feb 19 23:01:48 2020 +0100

    ...

commit 05990267b46a3aa79e5627c330cfa3a4b8838b5d
Author: Christian Schrötter <cs@fnx.li>
Date:   Wed Feb 19 22:51:22 2020 +0100

    ...

commit 68e4a8cff0cc960e561976ea36bc66842f2eeb82
Author: Christian Schrötter <cs@fnx.li>
Date:   Wed Feb 19 22:38:18 2020 +0100

    ...

commit 5d52165f66f397ac49e3156f04c1b3ba620a30db
Author: Christian Schrötter <cs@fnx.li>
Date:   Wed Feb 19 18:08:12 2020 +0100

    ...

commit a80cd52417e88dca4b7b9beb9381a499e4471047
Author: Christian Schrötter <cs@fnx.li>
Date:   Wed Feb 19 17:27:06 2020 +0100

    FFM: Check ghost hash too (same result ghosts)

commit 551f18b03f7c6ce4506b9bda93fbe616dbe636cf
Author: Christian Schrötter <cs@fnx.li>
Date:   Wed Feb 19 17:05:40 2020 +0100

    ...

commit 8be0c278ab8afcb18fa39d3150316fc38c0ebadd
Author: Christian Schrötter <cs@fnx.li>
Date:   Wed Feb 19 02:12:38 2020 +0100

    ...

commit c275439c357810d19421b4d4597b86812fd00459
Author: Christian Schrötter <cs@fnx.li>
Date:   Fri Feb 14 16:39:50 2020 +0100

    Resize FFM dialog after status update

commit 372b605f245658fda2e9c243f0544412e8e841c1
Author: Christian Schrötter <cs@fnx.li>
Date:   Thu Feb 13 21:52:28 2020 +0100

    ...

commit 3db06e4d7aabc505256f3296cc4094d25d426c8e
Author: Christian Schrötter <cs@fnx.li>
Date:   Thu Feb 13 21:28:21 2020 +0100

    Fix last commit

commit ec67ca9902b0e53c0869ec5fda8c6904607520dc
Author: Christian Schrötter <cs@fnx.li>
Date:   Thu Feb 13 21:13:11 2020 +0100

    Possible fix for NoSuchMethodError exception at JRE 1.8

commit 12ce23b0489a1b0147bf26a576f33a106d1f6d29
Author: Christian Schrötter <cs@fnx.li>
Date:   Thu Feb 13 21:02:55 2020 +0100

    Possible fix for class version mismatch (52/55) at JRE 1.8

commit 48604b3f7cc3bffa2cc30db408e0c056e206c9a6
Author: Christian Schrötter <cs@fnx.li>
Date:   Thu Feb 13 18:19:15 2020 +0100

    Implement WatchService for FFM

commit 9bbaf95e203ffbfad25467b9d6c8062d5efd5d08
Author: Christian Schrötter <cs@fnx.li>
Date:   Thu Feb 13 17:12:34 2020 +0100

    ...

commit 18e12dadc70031e54178254815d396bac10723f3
Author: Christian Schrötter <cs@fnx.li>
Date:   Wed Feb 12 00:06:22 2020 +0100

    ...

commit d20a4ae9e6223e7af642500297d425da16417983
Author: Christian Schrötter <cs@fnx.li>
Date:   Tue Feb 11 23:25:59 2020 +0100

    ...

commit 082d01db3aa53bf9f1753e2017fa90655c627106
Author: Christian Schrötter <cs@fnx.li>
Date:   Tue Feb 11 22:47:32 2020 +0100

    ...

commit 4abce6e4eee6eae1b8fe294b9ebde9ee81b2f6b0
Author: Christian Schrötter <cs@fnx.li>
Date:   Tue Feb 11 22:45:54 2020 +0100

    ...

commit d91cf530bae722a968f6d1c1ef08db54d54efc34
Author: Christian Schrötter <cs@fnx.li>
Date:   Tue Feb 11 22:33:07 2020 +0100

    ...

commit 939962e796e3987e376680c7c6c3681339966c32
Author: Christian Schrötter <cs@fnx.li>
Date:   Tue Feb 11 08:54:46 2020 +0100

    ...

commit c2a9a8e3979aaf016a6d829d2414dacdb31014b5
Author: Christian Schrötter <cs@fnx.li>
Date:   Tue Feb 11 07:00:37 2020 +0100

    ...

commit d829e2b0f1851680b82c755cf067891931c56067
Author: Christian Schrötter <cs@fnx.li>
Date:   Tue Feb 11 04:09:44 2020 +0100

    ...

commit 7cfb56e6bb3644b28fab11d4e1778f67df1e649d
Author: Christian Schrötter <cs@fnx.li>
Date:   Tue Feb 11 03:44:16 2020 +0100

    ...

commit 6624bc74b7a4d0cd16b4da6bc5f7e028910d3620
Author: Christian Schrötter <cs@fnx.li>
Date:   Tue Feb 11 03:33:46 2020 +0100

    ...

commit 845977bf6ff9fd5176bcfe0142e444172131ca90
Author: Christian Schrötter <cs@fnx.li>
Date:   Tue Feb 11 01:54:17 2020 +0100

    s/2019/2020/

commit 37595f6bac34d996603ba8a35cd57895702f383b
Author: Christian Schrötter <cs@fnx.li>
Date:   Tue Feb 4 06:34:13 2020 +0100

    ...

commit 4e8dd9673651147bf8d3fe34e1ddc0b2d781ea1f
Author: Christian Schrötter <cs@fnx.li>
Date:   Tue Feb 4 05:44:21 2020 +0100

    ...

commit ac2d9cd6cd06fb527a08819cb210f576536ee095
Author: Christian Schrötter <cs@fnx.li>
Date:   Tue Feb 4 05:14:05 2020 +0100

    Do not change country if language is identical

commit 1f5a2e02e9f8f7e8969a8f04eac81c3c1730ebe9
Author: Christian Schrötter <cs@fnx.li>
Date:   Tue Feb 4 05:01:39 2020 +0100

    ...

commit 0bee5caa5cdbac266c7b911693928db3eb45e580
Author: Christian Schrötter <cs@fnx.li>
Date:   Tue Feb 4 04:50:51 2020 +0100

    ...

commit 5101cb5d91e5a4e7be8e358054ddb5a48c80fd85
Author: Christian Schrötter <cs@fnx.li>
Date:   Fri Jan 31 01:26:00 2020 +0100

    ...

commit aa306ba144b50ad2a3b33510109b57ef70b4b36e
Author: Christian Schrötter <cs@fnx.li>
Date:   Fri Jan 31 01:18:32 2020 +0100

    ...

commit de07e69d0c3f6830cfc96e717de71dc49d2ecfce
Author: Christian Schrötter <cs@fnx.li>
Date:   Fri Jan 31 01:12:23 2020 +0100

    ...

commit b1a0c591440d3ee79707a16d69496dd5d09d2545
Author: Christian Schrötter <cs@fnx.li>
Date:   Thu Jan 30 20:51:48 2020 +0100

    ...

commit 41e6b580cf1cf14ef7d62c4aff011d0460b00fb6
Author: Christian Schrötter <cs@fnx.li>
Date:   Thu Jan 30 19:22:14 2020 +0100

    ...

commit 5fbb3ae1669d66f56eace588d4d5c23c57083823
Author: Christian Schrötter <cs@fnx.li>
Date:   Thu Jan 30 19:07:00 2020 +0100

    ...

commit 9eb6dc0b523794057e422db3ef4dcf8bd5107553
Author: Christian Schrötter <cs@fnx.li>
Date:   Thu Jan 30 18:41:05 2020 +0100

    ...

commit 541ac5128183d865e90f44fa2167a00ad18a567c
Author: Christian Schrötter <cs@fnx.li>
Date:   Thu Jan 30 18:39:42 2020 +0100

    ...

commit 0184bd65a975442dec860cc99b268e8bf68b8935
Author: Christian Schrötter <cs@fnx.li>
Date:   Thu Jan 30 06:08:34 2020 +0100

    ...

commit da8c2eed7a8e971f454bc30b16db9f59b2e451d5
Author: Christian Schrötter <cs@fnx.li>
Date:   Thu Jan 30 05:52:45 2020 +0100

    ...

commit 2a83f92e280d399723f9d44f60047e7179fe56bf
Author: Christian Schrötter <cs@fnx.li>
Date:   Thu Jan 30 05:49:59 2020 +0100

    ...

commit ad93388ac490654da5b15f04fe602546d5d17d3e
Author: Christian Schrötter <cs@fnx.li>
Date:   Thu Jan 30 03:18:39 2020 +0100

    ...

commit 4181c2a20a223eb65fd0b616a2f6095bc3a09698
Author: Christian Schrötter <cs@fnx.li>
Date:   Wed Jan 29 23:50:07 2020 +0100

    ...

commit 98423128904a74dbf5482698a8b232fb62369582
Author: Christian Schrötter <cs@fnx.li>
Date:   Wed Jan 29 18:53:22 2020 +0100

    ...

commit c6ee30c169985cedf1175d0d9a1ab3dabe98e39b
Author: Christian Schrötter <cs@fnx.li>
Date:   Wed Jan 29 18:52:02 2020 +0100

    ...

commit 2efa030470503530387d399b8cd1f7f5d355718e
Author: Christian Schrötter <cs@fnx.li>
Date:   Wed Jan 29 00:23:25 2020 +0100

    ...

commit accfd66ccb98e63f15be4069395966f6a6178da8
Author: Christian Schrötter <cs@fnx.li>
Date:   Tue Jan 28 18:36:23 2020 +0100

    ...

commit ef17b9a21a37cb7a98b67931e887979339afeb3b
Author: Christian Schrötter <cs@fnx.li>
Date:   Tue Jan 28 17:17:53 2020 +0100

    Display thread ID and type (root/event/worker) in debug messages

commit 8392e65b3b5a10d343a4b6136978e71bf4c9f9ac
Author: Christian Schrötter <cs@fnx.li>
Date:   Tue Jan 28 16:00:59 2020 +0100

    ...

commit 5cbd6ce65d13b9370f1369a9d4f2de532ecf3290
Author: Christian Schrötter <cs@fnx.li>
Date:   Tue Jan 28 04:05:54 2020 +0100

    ...

commit 48fa4d11ea9349482c149bd46a82239dc131932d
Author: Christian Schrötter <cs@fnx.li>
Date:   Tue Jan 28 03:52:22 2020 +0100

    ...